export interface MockLead {
  id: string;
  time: string;
  has_eviction_lawsuit: boolean;
  issue_description: string;
  email: string;
  full_name: string;
  phone_number: string;
  street_address: string;
  comments: string;
  called_status: string;
  texted_status: string;
  followed_up_notes: string;
  handoff_to: string;
  nyscef_link: string;
  retainer_amount: number | null;
  signed: boolean;
}

export const mockLeadsData: MockLead[] = [
  {
    id: "1",
    time: "8:14pm",
    has_eviction_lawsuit: true,
    issue_description: "I was in arrears couldn't afford to pay got evicted and the landlord sued me. Was out of work for a year on disability and likely to go back out due to aggravation of injuries.",
    email: "example@yahoo.com",
    full_name: "John Doe",
    phone_number: "+191711234567",
    street_address: "123 Main St, Apt 4B",
    comments: "Urgent eviction case, needs immediate review.",
    called_status: "VOICE CALL",
    texted_status: "TEXT Kian",
    followed_up_notes: "[06/28 2:33 PM] Client wants to meet tomorrow.",
    handoff_to: "KIAN",
    nyscef_link: "https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=123",
    retainer_amount: 1500,
    signed: true,
  },
  {
    id: "2",
    time: "9:30am",
    has_eviction_lawsuit: false,
    issue_description: "Landlord refusing to fix severe mold and no heat in winter.",
    email: "sarah.smith@gmail.com",
    full_name: "Sarah Smith",
    phone_number: "+19172345678",
    street_address: "456 Oak Ave, Brooklyn",
    comments: "CALL BACK MONDAY",
    called_status: "VOICE CALL MESSAGED",
    texted_status: "TEXT Haley",
    followed_up_notes: "7 months dealing with issue. Did not want our services. DISREGARD\n[07/07 8:49 AM] Trying again next week.",
    handoff_to: "HALEY",
    nyscef_link: "",
    retainer_amount: null,
    signed: false,
  },
  {
    id: "3",
    time: "11:45am",
    has_eviction_lawsuit: true,
    issue_description: "Getting evicted when landlord never made repairs and left us living in mold infested apartment.",
    email: "m.johnson@example.com",
    full_name: "Michael Johnson",
    phone_number: "+13475550198",
    street_address: "789 Pine Rd, Bronx",
    comments: "Pending court date.",
    called_status: "NO ANSWER",
    texted_status: "🔴",
    followed_up_notes: "had a teleconfernce 6/26 - Client didn't show up.",
    handoff_to: "MEHER",
    nyscef_link: "",
    retainer_amount: null,
    signed: false,
  },
  {
    id: "4",
    time: "2:10pm",
    has_eviction_lawsuit: false,
    issue_description: "Lease renewal dispute. They want to raise rent by 40%.",
    email: "amy.williams@hotmail.com",
    full_name: "Amy Williams",
    phone_number: "+16465551234",
    street_address: "321 Elm St, Queens",
    comments: "",
    called_status: "BUSY",
    texted_status: "TEXT Justin",
    followed_up_notes: "",
    handoff_to: "JUSTIN",
    nyscef_link: "https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=456",
    retainer_amount: 500,
    signed: true,
  },
  {
    id: "5",
    time: "4:00pm",
    has_eviction_lawsuit: true,
    issue_description: "Holdover case. Landlord claims I have a dog but it's an ESA.",
    email: "david.brown@gmail.com",
    full_name: "David Brown",
    phone_number: "+12125559876",
    street_address: "654 Cedar Ln, Manhattan",
    comments: "Client has all ESA documentation ready.",
    called_status: "WRONG NUMBER",
    texted_status: "YLP AUTO TEXT",
    followed_up_notes: "[08/12 10:00 AM] Re-sent text to correct number provided via email.",
    handoff_to: "KYLA",
    nyscef_link: "https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=789",
    retainer_amount: 2500,
    signed: false,
  },
  {
    id: "6",
    time: "5:30pm",
    has_eviction_lawsuit: false,
    issue_description: "Just need general advice on breaking a lease early due to job relocation.",
    email: "robert.davis@company.com",
    full_name: "Robert Davis",
    phone_number: "+19175554321",
    street_address: "987 Maple Dr, Staten Island",
    comments: "Needs consultation only.",
    called_status: "VOICE CALL",
    texted_status: "NO TEXT NECESSARY",
    followed_up_notes: "Consultation scheduled for Friday.",
    handoff_to: "HALEY",
    nyscef_link: "",
    retainer_amount: 250,
    signed: true,
  },
  {
    id: "7",
    time: "8:00am",
    has_eviction_lawsuit: true,
    issue_description: "Non-payment eviction but I have been withholding rent due to severe leaks destroying my furniture.",
    email: "lisa.garcia@outlook.com",
    full_name: "Lisa Garcia",
    phone_number: "+13475558765",
    street_address: "159 Birch Ct, Brooklyn",
    comments: "Has photos of damage.",
    called_status: "",
    texted_status: "CURRENT CLIENT",
    followed_up_notes: "Working on warranty of habitability defense.",
    handoff_to: "JUSTIN",
    nyscef_link: "https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=101",
    retainer_amount: 3000,
    signed: true,
  },
  {
    id: "8",
    time: "10:22am",
    has_eviction_lawsuit: false,
    issue_description: "Security deposit return issue. Moved out 2 months ago and landlord is ignoring my calls.",
    email: "james.wilson@mail.com",
    full_name: "James Wilson",
    phone_number: "+16465552468",
    street_address: "753 Walnut St, Queens",
    comments: "Small claims potential.",
    called_status: "NO ANSWER",
    texted_status: "TEXT Kyla ",
    followed_up_notes: "[09/01 1:15 PM] Left voicemail and sent follow-up text.",
    handoff_to: "KYLA",
    nyscef_link: "",
    retainer_amount: null,
    signed: false,
  }
];
