"""Initial migration with all tables

Revision ID: 7f1a55896611
Revises: 
Create Date: 2026-02-23 22:24:28.867222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1a55896611'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('email_encrypted', sa.Text(), nullable=False),
    sa.Column('app_password_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('identifier_snippet', sa.String(length=500), nullable=False),
    sa.Column('name_regex', sa.String(length=500), nullable=False),
    sa.Column('phone_regex', sa.String(length=500), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('auto_respond_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_sources_sender_email'), 'lead_sources', ['sender_email'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('source_email', sa.String(length=255), nullable=False),
    sa.Column('lead_source_id', sa.Integer(), nullable=False),
    sa.Column('gmail_uid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('response_sent', sa.Boolean(), nullable=True),
    sa.Column('response_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lead_source_id'], ['lead_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_gmail_uid'), 'leads', ['gmail_uid'], unique=True)
    op.create_index(op.f('ix_leads_source_email'), 'leads', ['source_email'], unique=False)
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_uid', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processing_log_query', 'processing_logs', ['timestamp', 'sender_email', 'status'], unique=False)
    op.create_index(op.f('ix_processing_logs_gmail_uid'), 'processing_logs', ['gmail_uid'], unique=False)
    op.create_index(op.f('ix_processing_logs_sender_email'), 'processing_logs', ['sender_email'], unique=False)
    op.create_index(op.f('ix_processing_logs_status'), 'processing_logs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_logs_timestamp'), 'processing_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_logs_timestamp'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_status'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_sender_email'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_gmail_uid'), table_name='processing_logs')
    op.drop_index('idx_processing_log_query', table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index(op.f('ix_leads_source_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_gmail_uid'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_lead_sources_sender_email'), table_name='lead_sources')
    op.drop_table('lead_sources')
    op.drop_table('templates')
    op.drop_table('credentials')
    # ### end Alembic commands ###
