"""Add processed_messages table

Revision ID: a1cc62a1c4a6
Revises: d2e3f4a5b6c7
Create Date: 2026-03-12 12:34:43.348195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cc62a1c4a6'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — only creates processed_messages table.

    NOTE: The destructive drop_table / drop_column statements that were
    auto-generated here have been intentionally removed.  Those tables
    (agent_users, form_templates, etc.) are created by earlier migrations
    and must not be dropped here.
    """
    # Use bind to check if table already exists (idempotent for re-runs)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'processed_messages' not in existing_tables:
        op.create_table(
            'processed_messages',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('agent_id', sa.String(length=255), nullable=False),
            sa.Column('message_id_hash', sa.String(length=64), nullable=False),
            sa.Column('processed_at', sa.DateTime(), nullable=False),
            sa.Column('lead_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('agent_id', 'message_id_hash', name='uq_processed_message'),
        )
        op.create_index('idx_processed_messages_agent', 'processed_messages', ['agent_id'], unique=False)
        op.create_index('idx_processed_messages_hash', 'processed_messages', ['message_id_hash'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_agent_action_at', sa.DATETIME(), nullable=True))
    op.add_column('leads', sa.Column('current_state', sa.VARCHAR(length=50), nullable=True))
    op.add_column('leads', sa.Column('lead_source_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('leads', sa.Column('score_bucket', sa.VARCHAR(length=7), nullable=True))
    op.add_column('leads', sa.Column('listing_url', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('leads', sa.Column('score_breakdown', sa.TEXT(), nullable=True))
    op.add_column('leads', sa.Column('agent_user_id', sa.INTEGER(), nullable=True))
    op.add_column('leads', sa.Column('score', sa.INTEGER(), nullable=True))
    op.add_column('leads', sa.Column('agent_current_state', sa.VARCHAR(length=15), server_default=sa.text("'NEW'"), nullable=True))
    op.add_column('leads', sa.Column('property_address', sa.VARCHAR(length=500), nullable=True))
    op.add_column('leads', sa.Column('company_id', sa.INTEGER(), nullable=True))
    op.add_column('leads', sa.Column('current_state_updated_at', sa.DATETIME(), nullable=True))
    op.create_table('lead_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('agent_user_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['agent_user_id'], ['agent_users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_lead_id_created_at'), 'lead_events', ['lead_id', 'created_at'], unique=False)
    op.create_table('scoring_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('intent_type', sa.VARCHAR(length=10), server_default=sa.text("'BUY'"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_configs_tenant_id'), 'scoring_configs', ['tenant_id'], unique=False)
    op.create_table('submission_scores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submission_id', sa.INTEGER(), nullable=False),
    sa.Column('total_score', sa.INTEGER(), nullable=False),
    sa.Column('bucket', sa.VARCHAR(length=20), nullable=False),
    sa.Column('breakdown_json', sa.TEXT(), nullable=False),
    sa.Column('explanation_text', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', name=op.f('uq_submission_scores_submission_id'))
    )
    op.create_table('form_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('intent_type', sa.VARCHAR(length=10), server_default=sa.text("'BUY'"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_templates_tenant_id'), 'form_templates', ['tenant_id'], unique=False)
    op.create_table('agent_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_user_id', sa.INTEGER(), nullable=False),
    sa.Column('template_type', sa.VARCHAR(length=14), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('tone', sa.VARCHAR(length=12), server_default=sa.text("'PROFESSIONAL'"), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('parent_template_id', sa.INTEGER(), nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['agent_users.id'], ),
    sa.ForeignKeyConstraint(['parent_template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_templates_user_type'), 'agent_templates', ['agent_user_id', 'template_type'], unique=False)
    op.create_table('lead_interactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('intent_type', sa.VARCHAR(length=10), server_default=sa.text("'BUY'"), nullable=False),
    sa.Column('channel', sa.VARCHAR(length=20), server_default=sa.text("'email'"), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), nullable=False),
    sa.Column('occurred_at', sa.DATETIME(), nullable=False),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('content_text', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_interactions_tenant_id'), 'lead_interactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lead_interactions_occurred_at'), 'lead_interactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_lead_interactions_lead_id'), 'lead_interactions', ['lead_id'], unique=False)
    op.create_table('submission_answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submission_id', sa.INTEGER(), nullable=False),
    sa.Column('question_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('answer_value_json', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_answers_submission_id'), 'submission_answers', ['submission_id'], unique=False)
    op.create_table('form_invitations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('intent_type', sa.VARCHAR(length=10), server_default=sa.text("'BUY'"), nullable=False),
    sa.Column('form_version_id', sa.INTEGER(), nullable=False),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), server_default=sa.text("'email'"), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_form_invitations_token_hash'))
    )
    op.create_index(op.f('ix_form_invitations_token_hash'), 'form_invitations', ['token_hash'], unique=1)
    op.create_index(op.f('ix_form_invitations_tenant_id'), 'form_invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_form_invitations_lead_id'), 'form_invitations', ['lead_id'], unique=False)
    op.create_table('message_template_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('subject_template', sa.VARCHAR(length=500), nullable=False),
    sa.Column('body_template', sa.TEXT(), nullable=False),
    sa.Column('variants_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_template_versions_template_id'), 'message_template_versions', ['template_id'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('intent_type', sa.VARCHAR(length=10), server_default=sa.text("'BUY'"), nullable=False),
    sa.Column('form_version_id', sa.INTEGER(), nullable=False),
    sa.Column('scoring_version_id', sa.INTEGER(), nullable=True),
    sa.Column('invitation_id', sa.INTEGER(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('time_to_submit_seconds', sa.INTEGER(), nullable=True),
    sa.Column('lead_source', sa.VARCHAR(length=255), nullable=True),
    sa.Column('property_address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('listing_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('repeat_inquiry_count', sa.INTEGER(), nullable=True),
    sa.Column('raw_payload_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['form_invitations.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['scoring_version_id'], ['scoring_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_tenant_id'), 'form_submissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_lead_id'), 'form_submissions', ['lead_id'], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('intent_type', sa.VARCHAR(length=10), server_default=sa.text("'BUY'"), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_tenant_id'), 'message_templates', ['tenant_id'], unique=False)
    op.create_table('agent_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=100), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('service_area', sa.TEXT(), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('credentials_id', sa.INTEGER(), nullable=True),
    sa.Column('onboarding_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('onboarding_step', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'agent'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['credentials_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lead_state_transitions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('intent_type', sa.VARCHAR(length=10), server_default=sa.text("'BUY'"), nullable=False),
    sa.Column('from_state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('to_state', sa.VARCHAR(length=50), nullable=False),
    sa.Column('occurred_at', sa.DATETIME(), nullable=False),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('actor_type', sa.VARCHAR(length=20), server_default=sa.text("'system'"), nullable=False),
    sa.Column('actor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_state_transitions_tenant_id'), 'lead_state_transitions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lead_state_transitions_occurred_at'), 'lead_state_transitions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_lead_state_transitions_lead_id_occurred_at'), 'lead_state_transitions', ['lead_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_lead_state_transitions_lead_id'), 'lead_state_transitions', ['lead_id'], unique=False)
    op.create_table('form_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('form_version_id', sa.INTEGER(), nullable=False),
    sa.Column('question_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('label', sa.VARCHAR(length=500), nullable=False),
    sa.Column('required', sa.BOOLEAN(), nullable=True),
    sa.Column('options_json', sa.TEXT(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('validation_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_questions_form_version_id'), 'form_questions', ['form_version_id'], unique=False)
    op.create_table('form_logic_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('form_version_id', sa.INTEGER(), nullable=False),
    sa.Column('rule_json', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_logic_rules_form_version_id'), 'form_logic_rules', ['form_version_id'], unique=False)
    op.create_table('scoring_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scoring_config_id', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('rules_json', sa.TEXT(), nullable=False),
    sa.Column('thresholds_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['scoring_config_id'], ['scoring_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_versions_scoring_config_id'), 'scoring_versions', ['scoring_config_id'], unique=False)
    op.create_table('buyer_automation_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_platform_default', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('hot_threshold', sa.INTEGER(), server_default=sa.text("'80'"), nullable=False),
    sa.Column('warm_threshold', sa.INTEGER(), server_default=sa.text("'50'"), nullable=False),
    sa.Column('weight_timeline', sa.INTEGER(), server_default=sa.text("'25'"), nullable=False),
    sa.Column('weight_preapproval', sa.INTEGER(), server_default=sa.text("'30'"), nullable=False),
    sa.Column('weight_phone_provided', sa.INTEGER(), server_default=sa.text("'15'"), nullable=False),
    sa.Column('weight_tour_interest', sa.INTEGER(), server_default=sa.text("'20'"), nullable=False),
    sa.Column('weight_budget_match', sa.INTEGER(), server_default=sa.text("'10'"), nullable=False),
    sa.Column('enable_tour_question', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('form_link_template', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['agent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('schema_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_versions_template_id'), 'form_versions', ['template_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('agent_user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('last_accessed', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['agent_user_id'], ['agent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_expires_at'), 'agent_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_agent_sessions_agent_user_id'), 'agent_sessions', ['agent_user_id'], unique=False)
    op.create_table('agent_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_user_id', sa.INTEGER(), nullable=False),
    sa.Column('hot_threshold', sa.INTEGER(), server_default=sa.text("'80'"), nullable=False),
    sa.Column('warm_threshold', sa.INTEGER(), server_default=sa.text("'50'"), nullable=False),
    sa.Column('sla_minutes_hot', sa.INTEGER(), server_default=sa.text("'5'"), nullable=False),
    sa.Column('quiet_hours_start', sa.TIME(), nullable=True),
    sa.Column('quiet_hours_end', sa.TIME(), nullable=True),
    sa.Column('working_days', sa.VARCHAR(length=20), server_default=sa.text("'MON-SAT'"), nullable=False),
    sa.Column('enable_tour_question', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('enabled_lead_source_ids', sa.TEXT(), nullable=True),
    sa.Column('buyer_automation_config_id', sa.INTEGER(), nullable=True),
    sa.Column('watcher_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('watcher_admin_override', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['agent_users.id'], ),
    sa.ForeignKeyConstraint(['buyer_automation_config_id'], ['buyer_automation_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_user_id')
    )
    op.drop_index('idx_processed_messages_hash', table_name='processed_messages')
    op.drop_index('idx_processed_messages_agent', table_name='processed_messages')
    op.drop_table('processed_messages')
    # ### end Alembic commands ###
